import { Info, Idea } from "@/components/Callout"

# Expected Errors

In this tutorial you will learn:

- How Effect represents expected errors
- The tools Effect provides for robust and comprehensive error management

As we saw in the tutorial [Create your first Effect](../getting-started/creating), we can use the `fail` constructor to create an Effect
that represents an error:

```ts
import * as Effect from "@effect/io/Effect"

class HttpError {
  readonly _tag = "HttpError"
}

const program: Effect.Effect<never, HttpError, never> = Effect.fail(
  new HttpError()
)
```

<Info>
  We use a class to represent the `HttpError` type above simply to gain access
  to both the error type and a free constructor. However, you can use whatever
  you like to model your error types.
</Info>

It's worth noting that we added a `_tag` field to our error in the example.

```ts /_tag/
class HttpError {
  readonly _tag = "HttpError"
}
```

<Idea>
  A discriminant field can be helpful for distinguishing between different types
  of errors during error handling and prevents TypeScript from unifying types.
</Idea>

Expected errors **are tracked** at the type level by the `Effect` data type in the "Error" channel.

It is evident from the type of `program` that can fail with an error of type `HttpError`:

```ts /HttpError/
Effect.Effect<never, HttpError, never>
```

## Error Accumulation

The following program serves as an illustration of how errors are automatically tracked and accumulated for you:

```ts
import * as Effect from "@effect/io/Effect"
import * as Random from "@effect/io/Random"
import { pipe } from "@effect/data/Function"

class FooError {
  readonly _tag = "FooError"
}

class BarError {
  readonly _tag = "BarError"
}

const flakyFoo = pipe(
  Random.next(),
  Effect.flatMap((n) =>
    n > 0.5 ? Effect.succeed("yay!") : Effect.fail(new FooError())
  )
)

const flakyBar = pipe(
  Random.next(),
  Effect.flatMap((n) =>
    n > 0.5 ? Effect.succeed("yay!") : Effect.fail(new BarError())
  )
)

const program: Effect.Effect<never, FooError | BarError, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar)
)
```

In the above program, we have two operations: `flakyFoo` and `flakyBar`, each representing a potential source of error.
These operations are combined using the `flatMap` function from the Effect library, which allows us to sequence them together.

Effect automatically keeps track of the possible errors that can occur during the execution of the program.
In this case, we have `FooError` and `BarError` as the possible error types.
The error channel of the `program` is specified as

```ts /FooError | BarError/
Effect.Effect<never, FooError | BarError, string>
```

indicating that it can potentially fail with either a `FooError` or a `BarError`.

By leveraging this error tracking mechanism, we can handle specific types of errors in a targeted manner.

## Catching

To handle errors in a simple way, you can use the `catchAll` function.

### catchAll

The `catchAll` function allows you to catch any error that occurs in the program and provide a fallback.

```ts {4}
const program: Effect.Effect<never, never, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar),
  Effect.catchAll((e) => Effect.succeed(`Recovering from ${e._tag}`))
)
```

We can observe that the type in the error channel of our `program` has changed to `never`,
indicating that all errors has been handled.

```ts /never/2
Effect.Effect<never, never, string>
```

### catchTag

Suppose we only want to handle `FooError`. In that case, we can use the `catchTag` method provided by Effect:

```ts {4-6}
const program: Effect.Effect<never, BarError, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar),
  Effect.catchTag("FooError", (fooError) =>
    Effect.succeed(`Recovering from ${fooError._tag}`)
  )
)
```

In the example above, the `catchTag` function allows us to handle `FooError` specifically.
If a `FooError` occurs during the execution of the program, the provided error handler function will be invoked,
and the program will proceed with the recovery logic specified within the handler.

We can observe that the type in the error channel of our `program` has changed to only show `BarError`,
indicating that `FooError` has been handled.

```ts /BarError/
Effect.Effect<never, BarError, string>
```

If we also wanted to handle `BarError`, we can simply add another `catchTag`.

```ts {7-9}
const program: Effect.Effect<never, never, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar),
  Effect.catchTag("FooError", (fooError) =>
    Effect.succeed(`Recovering from ${fooError._tag}`)
  ),
  Effect.catchTag("BarError", (barError) =>
    Effect.succeed(`Recovering from ${barError._tag}`)
  )
)
```

### catchTags

Instead of using the `catchTag` combinator multiple times to handle individual error types, we have a more convenient option called `catchTags`. With `catchTags`, we can handle multiple errors in a single block of code.

```ts {4-7}
const program: Effect.Effect<never, never, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar),
  Effect.catchTags({
    FooError: (fooError) => Effect.succeed(`Recovering from ${fooError._tag}`),
    BarError: (barError) => Effect.succeed(`Recovering from ${barError._tag}`),
  })
)
```

In the above example, instead of using `catchTag` multiple times to handle individual errors, we utilize the `catchTags` combinator.
This combinator takes an object where each property represents a specific error `_tag` (`"FooError"` and `"BarError"` in this case),
and the corresponding value is the error handler function to be executed when that particular error occurs.

## Modifying

Sometimes, instead of handling an error directly, you may need to transform or modify it in some way.
This can involve adding extra information to the error or changing its type altogether.
In such cases, you can use the `mapError` function.

```ts {4-10}
const program: Effect.Effect<never, Error, string> = pipe(
  flakyFoo,
  Effect.flatMap(() => flakyBar),
  Effect.mapError((error) => {
    if (error._tag === "FooError") {
      return new Error("Something went wrong with Foo")
    } else {
      return new Error("Something went wrong with Bar")
    }
  })
)
```

We can observe that the type in the error channel of our `program` has changed from `FooError | BarError` to `Error`.

```ts /Error/
Effect.Effect<never, Error, string>
```

In the code snippet above, `mapError` is applied to the `Effect` computation.
It allows us to transform the error produced by the computation while keeping the success value unchanged.
The provided error transformation function takes the original error as an input and returns a new error.

In this example, we check the `_tag` field of the error to determine its type (`FooError` or `BarError`).
Depending on the type, we create a new error object with a modified message.
This enables us to add specific information or customize the error representation based on the encountered error type.

By utilizing `mapError`, you can manipulate the error channel of an `Effect` computation, tailoring it to your specific requirements.
This can be particularly useful when you need to adapt error types, enrich error messages,
or perform other error-related transformations while preserving the main logic and success pathway of your program.
