import { Info, Idea, Error } from "@/components/Callout"

# Creating Effects

Effect provides different ways to create effects, which are units of computation that encapsulate side effects.
In this tutorial, we will cover some of the common methods that you can use to create effects.

## Why Not Throw Errors?

In traditional programming, when an error occurs, it is often handled by throwing an exception:

```ts
const divide = (a: number, b: number): number => {
  if (b === 0) {
    throw new Error("Cannot divide by zero")
  }
  return a / b
}
```

However, throwing errors can be problematic. The type signatures of functions do not indicate that they can throw exceptions, making it difficult to reason about potential errors.

To address this issue, the `@effect/io/Effect` module introduces dedicated constructors for creating effects that represent both success and failure: `Effect.succeed` and `Effect.fail`. These constructors allow you to explicitly handle success and failure cases while **leveraging the type system to track errors**.

### `Effect.succeed`

To create an effect that represents a successful computation, you can use the `Effect.succeed` constructor. It takes a value as input and produces an effect that succeeds with that value. Here's an example:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.succeed(42)
```

The `program` value has the type `Effect<never, never, number>` and can be interpreted as an effect that:

- does not require any context (`never`)
- does not produce any expected error (`never`)
- succeeds with a value of type `number`

### `Effect.fail`

To create an effect that represents a failure, you can use the `Effect.fail` constructor. It takes an error value as input and produces an effect that fails with that error. Here's an example:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, string, never>
const program = Effect.fail("my error")
```

The `program` value has the type `Effect<never, string, never>` and can be interpreted as an effect that:

- does not require any context (`never`)
- fails with an expected error of type `string`
- does not produce any value (`never`)

By using `Effect.succeed` and `Effect.fail`, you can explicitly handle success and failure cases and the type system ensures that errors are tracked and accounted for.

Let's see an example of rewriting the `divide` function using Effect to make the error handling explicit:

```ts
import * as Effect from "@effect/io/Effect"

const divide = (a: number, b: number): Effect.Effect<never, Error, number> =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)
```

In this example, the `divide` function explicitly indicates that it can produce an effect that either fails with an `Error` or succeeds with a `number` value. The type signature makes it clear how errors are handled and ensures that callers are aware of the possible outcomes.

## Modeling Synchronous Effects

In JavaScript, you can delay the execution of a synchronous computation using a "thunk".

<Info>
  A "thunk" is a function that takes no arguments and may return some value.
</Info>

Thunks are useful for delaying the computation of a value until it is needed.

To model synchronous side effects, Effect provides the `Effect.sync` and `Effect.try` constructors, which accept a thunk.

### Effect.sync

You can create an `Effect` from a thunk using the `Effect.sync` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.sync(() => {
  console.log("Hello, World!") // side effect
  return 42 // return value
})
```

In the above example, `Effect.sync` is used to defer the side-effect of writing to the console.
The `program` value has the type `Effect<never, never, number>` because the thunk returns the value `42`.

Note that nothing is logged to the console yet when you inspect it.
This is because `program` represents the action of writing to the console, but nothing happens until you explicitly run your program.

<Error>The thunk passed to `sync` should never throw errors.</Error>

### Effect.try

If the synchronous computation within the thunk may throw an error, you can use the `Effect.try` constructor.
If an error is caught, it will be propagated to the error channel as `unknown`:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, unknown, any>
const program = Effect.try(
  () => JSON.parse("") // JSON.parse may throw for bad input
)
```

If you want more control over what gets propagated to the error channel, you can use an overload of `Effect.try` that takes a remapping function:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, Error, any>
const program = Effect.try({
  try: () => JSON.parse(""), // JSON.parse may throw for bad input
  catch: (unknown) => new Error(`something went wrong ${unknown}`), // remap the error
})
```

You can think of this as a similar pattern to the traditional try-catch block in JavaScript:

```ts
try {
  return JSON.parse("")
} catch (unknown) {
  throw new Error(`something went wrong ${unknown}`)
}
```

## Modeling Asynchronous Effects

To model asynchronous side effects, Effect provides the `Effect.promise` and `Effect.tryPromise` constructors, which accept a thunk that returns a `Promise`.

### Effect.promise

If you're dealing with asynchronous side effects that return a `Promise`, you can use the `Effect.promise` constructor:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, never, number>
const program = Effect.promise(() => new Promise((resolve) => {
  setTimeout(() => {
    resolve("Async operation completed successfully!")
  }, 2000)
})
```

<Error>The `Promise` passed to `promise` should never reject.</Error>

### Effect.tryPromise

If the `Promise` within the thunk may reject, you can use the `Effect.tryPromise` constructor.
If an error is caught, it will be propagated to the error channel as `unknown`:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, unknown, Response>
const program = Effect.tryPromise(() =>
  fetch("https://jsonplaceholder.typicode.com/todos/1")
)
```

If you want more control over what gets propagated to the error channel, you can use an overload of `Effect.tryPromise` that takes a remapping function:

```ts
import * as Effect from "@effect/io/Effect"

// Effect<never, Error, Response>
const program = Effect.tryPromise({
  try: () => fetch("https://jsonplaceholder.typicode.com/todos/1"),
  catch: (unknown) => new Error(`something went wrong ${unknown}`), // remap the error
})
```

## From a callback

Sometimes you have to work with APIs that don't support `async/await` or `Promise` and instead use the callback style.
To handle callback-based APIs, Effect provides the `Effect.async` constructor.

For example, let's wrap the `readFile` async API from the Node.js `fs` module with Effect:

```ts
import * as Effect from "@effect/io/Effect"
import * as NodeFS from "node:fs"

// Effect<never, NodeJS.ErrnoException, Buffer>
const program = Effect.async<never, NodeJS.ErrnoException, Buffer>((resume) => {
  NodeFS.readFile("todos.txt", (error, data) => {
    if (error) {
      resume(Effect.fail(error))
    } else {
      resume(Effect.succeed(data))
    }
  })
})
```

In the above example, we manually annotate the types when calling `Effect.async` because TypeScript cannot infer the type parameters for a callback
based on the return value inside the callback body. Annotating the types ensures that the values provided to `resume` match the expected types.

<Idea>
  You can seamlessly mix synchronous and asynchronous code within the Effect
  framework. Everything becomes an Effect, enabling you to handle different
  types of side effects in a unified way.
</Idea>

## Cheatsheet

The table provides a summary of the available constructors, along with their input and output types, allowing you to choose the appropriate function based on your needs.

| **Function**            | **Given**                          | **To**                      |
| ----------------------- | ---------------------------------- | --------------------------- |
| `succeed`               | `A`                                | `Effect<never, never, A>`   |
| `fail`                  | `E`                                | `Effect<never, E, never>`   |
| `sync`                  | `() => A`                          | `Effect<never, never, A>`   |
| `try`                   | `() => A`                          | `Effect<never, unknown, A>` |
| `try` (overload)        | `() => A`, `unknown => E`          | `Effect<never, E, A>`       |
| `tryPromise`            | `() => Promise<A>`                 | `Effect<never, unknown, A>` |
| `tryPromise` (overload) | `() => Promise<A>`, `unknown => E` | `Effect<never, E, A>`       |
| `async`                 | `Effect<never, E, A> => void`      | `Effect<never, E, A>`       |

You can find the complete list of constructors [here](https://effect-ts.github.io/io/modules/Effect.ts.html#constructors).

Now that we know how to create effects, it's time to learn how to run them.
Check out the next tutorial on [Running Effects](running) to find out more.
