import { Design, Warning } from "@/components/Callout"

# Running Effects

To execute an `Effect`, we can utilize a variety of "run" functions provided by the `@effect/io/Effect` module.

## runSync

The `runSync` function is used to execute an Effect synchronously, which means it runs immediately and returns the result.

```ts
import { Effect } from "effect"

// Effect<never, never, number>
const program = Effect.sync(() => {
  console.log("Hello, World!")
  return 1
})

// number
const result = Effect.runSync(program)
// Output: Hello, World!

console.log(result)
// Output: 1
```

If you check the console, you will see the message `"Hello, World!"` printed.

<Warning>
  `runSync` will throw an error if your Effect fails or performs any
  asynchronous tasks. In the latter case, the execution will not proceed beyond
  that asynchronous task.
</Warning>

```ts
import { Effect } from "effect"

Effect.runSync(Effect.fail("error")) // throws

Effect.runSync(Effect.promise(() => Promise.resolve(1))) // throws
```

## runSyncExit

The `runSyncExit` function is used to execute an Effect synchronously, which means it runs immediately and returns the result as an [`Exit`](exit)
(a data type used to describe the result of executing an `Effect` workflow).

```ts
import { Effect } from "effect"

Effect.runSyncExit(Effect.succeed(1)) // Exit.succeed(1)

Effect.runSyncExit(Effect.fail("error")) // Exit.fail(...)
```

<Warning>
  `runSyncExit` will throw an error if your Effect performs any asynchronous
  tasks and the execution will not proceed beyond that asynchronous task.
</Warning>

```ts
import { Effect } from "effect"

Effect.runSyncExit(Effect.promise(() => Promise.resolve(1))) // throws
```

## runPromise

The `runPromise` function is used to execute an Effect and obtain the result as a `Promise`.

```ts
import { Effect } from "effect"

await Effect.runPromise(Effect.succeed(1)) // 1
```

<Warning>`runPromise` will reject with an error if your Effect fails</Warning>

```ts
import { Effect } from "effect"

Effect.runPromise(Effect.fail("error")) // rejects
```

## runPromiseExit

The `runPromiseExit` function is used to execute an Effect and obtain the result as a `Promise` that resolves to an [`Exit`](exit)
(a data type used to describe the result of executing an `Effect` workflow).

```ts
import { Effect } from "effect"

await Effect.runPromiseExit(Effect.succeed(1)) // Exit.succeed(1)

await Effect.runPromiseExit(Effect.fail("error")) // Exit.fail(...)
```

## Cheatsheet

<Design>
  The recommended approach is to design your program with the majority of its
  logic as Effects. It's advisable to use the `run*` functions closer to the
  "edge" of your program. This approach allows for greater flexibility in
  executing your program and building sophisticated Effects.
</Design>

The table provides a summary of the available `run*` functions, along with their input and output types, allowing you to choose the appropriate function based on your needs.

| **Name**         | **Given**             | **To**                |
| ---------------- | --------------------- | --------------------- |
| `runSync`        | `Effect<never, E, A>` | `A`                   |
| `runSyncExit`    | `Effect<never, E, A>` | `Exit<E, A>`          |
| `runPromise`     | `Effect<never, E, A>` | `Promise<A>`          |
| `runPromiseExit` | `Effect<never, E, A>` | `Promise<Exit<E, A>>` |

You can find the complete list of `run*` functions [here](https://effect-ts.github.io/io/modules/Effect.ts.html#execution).

In the next tutorial, we will learn how to build more complex programs by creating **pipelines**.

---
